### ISSUE TITLE
ziggy:generate doesn't worked with a cached routes file containing route closures - Function () does not exist error when running ziggy:generate

### ISSUE THREAD

**Issue by kyranb** [tighten/ziggy#364]
#### Description

Running `php artisan ziggy:generate` works on my local machine.

In production I get  the following error: `Function () does not exist {"exception":"[object] (ReflectionException(code: 0): Function () does not exist at `

```

Function () does not exist {"exception":"[object] (ReflectionException(code: 0): Function () does not exist at /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:23)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php(23): ReflectionFunction->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(507): Illuminate\\Routing\\RouteSignatureParameters::fromAction()
#2 /var/www/html/vendor/tightenco/ziggy/src/Ziggy.php(152): Illuminate\\Routing\\Route->signatureParameters()
#3 /var/www/html/vendor/tightenco/ziggy/src/Ziggy.php(94): Tightenco\\Ziggy\\Ziggy->resolveBindings()
#4 /var/www/html/vendor/tightenco/ziggy/src/Ziggy.php(25): Tightenco\\Ziggy\\Ziggy->nameKeyedRoutes()
#5 /var/www/html/vendor/tightenco/ziggy/src/CommandRouteGenerator.php(37): Tightenco\\Ziggy\\Ziggy->__construct()
#6 /var/www/html/vendor/tightenco/ziggy/src/CommandRouteGenerator.php(27): Tightenco\\Ziggy\\CommandRouteGenerator->generate()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Tightenco\\Ziggy\\CommandRouteGenerator->handle()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#13 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /var/www/html/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#20 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
```

#### Expected behavior

I'd expect the Ziggy routes file to be generated as in production. 

#### Environment

- **Laravel version**: 
v8.14.0
- **Ziggy version**: 
v1.0.2
**Related routes**:

**Ziggy call and context**:

`php artisan ziggy:generate`

As far as I'm aware there are no big differences between the production and my local environment. Any insight into what's causing this error and how to go about debugging further would be appreciated, but by no means expected :)

**Comment by bakerkretzmar** [comment]
Can you share the `require-dev` section of your `composer.json`? Are your local environment and production on the same PHP version?

`Function ()` is super weird and makes me think it might have to do with routes that are Closures and/or use short arrow functions, do you have any like that?

**Comment by kyranb** [comment]
Thanks @bakerkretzmar :) 

Yes, I do have a bunch that look like this for handling redirects:

```
Route::domain(config('app.old-domain'))->middleware('custom')->group(function () {
Route::get('/{id}/model', function ($id) {
        return redirect(('https://' . $id . '.' . config('app.new-domain') . '/model'));
    });
});
```

Here's the require-dev
```
  "require-dev": {
    "barryvdh/laravel-debugbar": "~3.5.1",
    "beyondcode/laravel-query-detector": "^1.1",
    "beyondcode/laravel-self-diagnosis": "^1.0",
    "codedungeon/phpunit-result-printer": "dev-master",
    "ergebnis/composer-normalize": "^2.2",
    "fruitcake/laravel-telescope-toolbar": "^1.2",
    "fzaninotto/faker": "^1.9",
    "laracademy/interactive-make": "^1.2",
    "laravel/browser-kit-testing": "^6.0",
    "laravel/dusk": "^6.4",
    "mockery/mockery": "^1.3.1",
    "nunomaduro/collision": "^5.0",
    "nunomaduro/larastan": "^0.6.0",
    "phpmd/phpmd": "^2.8",
    "phpstan/phpstan": "^0.12.11",
    "phpunit/phpunit": "^9.0",
    "sebastian/phpcpd": "^5.0",
    "squizlabs/php_codesniffer": "*",
    "themsaid/laravel-mail-preview": "^4.0",
    "timacdonald/log-fake": "^1.7",
    "vimeo/psalm": "^4.0",
    "wnx/laravel-stats": "^2.2"
  }
```

**Comment by kyranb** [comment]
Just an update, I've found that running:

`php artisan route:clear && php artisan ziggy:generate` works.

But `php artisan ziggy:generate` by itself does not.

**Comment by bakerkretzmar** [comment]
@kyranb is there any chance you have a syntax/formatting error in the definition of any of your routes? Something like https://laracasts.com/discuss/channels/laravel/function-does-not-exist?page=0 or https://laracasts.com/discuss/channels/laravel/function-does-not-exist-1?

If not, can you share _all_ your application routes or narrow down which specific one is causing this error and share that? I can't reproduce this issue with the example you gave above.

**Comment by rognales** [comment]
I had the same exact issue. What i did is to eliminate the routes one-by-one to find the problematic route and work from there.

**Comment by bakerkretzmar** [comment]
I'm pretty sure this isn't an issue with Ziggy, but please feel free to comment here again or open a new issue if you're able to reproduce it!

**Comment by michaelklopf** [comment]
Hey, I would like to add another example of the problem which was solved by correctly calling an invokable controller.

Did not work
```php
Route::patch('/user/clear', [ClearUserController::class])->name('maintained-by.clear');
```

Fixed it
```php
Route::patch('/user/clear', ClearUserController::class)->name('maintained-by.clear');
```

**Comment by snake-py** [comment]
I am seeing this error when I am adding a name attribute to my route?

```php
    Route::post('open-dashboard', [SuperAdminController::class => 'dashboard']); //->name('open-dashboard');
```
with name it does not work anymore

**Comment by danbower** [comment]
I was encountering this issue with hundreds of route definitions within an old code base so manually tracking it down was tricky.

I recommend temporarily modifying `vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php` to `try-catch` the error to see exactly which route is invalid. e.g. 

```
try {
    $parameters = is_string($callback)
        ? static::fromClassMethodString($callback)
        : (new ReflectionFunction($callback))->getParameters();
} catch (\Throwable $t) {
    print_r($action);
    throw $t;
}
```

**Comment by lipflip** [comment]
> vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php

This saved my day!!!
