### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by DanielvdSpoel** [tighten/ziggy#767]
### Ziggy version

11.19

### Laravel version

2.3.0

### Description

I have this Inertia/Vue3 setup:

`import { ZiggyVue } from '../../vendor/tightenco/ziggy'

const appName = import.meta.env.VITE_APP_NAME || 'Laravel'

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) =>
        resolvePageComponent(
            `./Pages/${name}.vue`,
            import.meta.glob<DefineComponent>('./Pages/**/*.vue')
        ),
    setup({ el, App, props, plugin }) {
        createApp({
            render: () => h(App, props),
        })
            .use(plugin)
            .use(ZiggyVue)
            .mount(el)
    },
    progress: {
        color: '#4B5563',
    },
})`

`
    public function share(Request $request): array
    {
        return [
            'ziggy' => fn () => [
                ...(new Ziggy)->toArray(),
                'location' => $request->url(),
            ],
        ];
    }`

However, whenever I try to get a route i get this error:
`index.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'home')
    at new N (index.js:1:10338)
    at T (index.js:1:15294)
    at Proxy.r (index.js:1:15376)
    at Home.vue:19:31
    at renderFnWithContext (chunk-YYVLN2RI.js?v=4d1bbd1a:2176:13)
    at renderSlot (chunk-YYVLN2RI.js?v=4d1bbd1a:3158:53)
    at Proxy._sfc_render (BaseLayout.vue:232:21)
    at renderComponentRoot (chunk-YYVLN2RI.js?v=4d1bbd1a:7758:17)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-YYVLN2RI.js?v=4d1bbd1a:6438:46)
    at ReactiveEffect.run (chunk-YYVLN2RI.js?v=4d1bbd1a:435:19)`

### Ziggy call and context

```js
import { Link } from '@inertiajs/vue3'
    <Link :href="route('home')"/>
```

### Ziggy configuration

```js
Not sure how to import the refereced Ziggy variable
```

### Route definition

```php
Route::get('/', function () {
    return inertia('Home');
})->name('home');
```

**Comment by DanielvdSpoel** [comment]
I'm stupid, forgot to include the routes directive/component in my blade layout
